

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ips = false
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
    
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024 
  end

  config.vm.define "puppet" do |puppet|
    #Puppet master on Centos7
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "puppet.example.com"
    puppet.vm.network :private_network, ip: "10.0.0.10"
    puppet.hostmanager.aliases = %w(puppet)
    puppet.vm.provision "shell", inline: <<-SHELL
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum update -y
      sudo yum install puppetserver -y
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
    SHELL
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "centos/7"
    agent1.vm.hostname = "agent1.example.com"
    agent1.vm.network :private_network, ip: "10.0.0.12"
    agent1.hostmanager.aliases = %w(agent1)
  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "ARTACK/debian-jessie"
    agent2.vm.hostname = "agent2.example.com"
    agent2.vm.network :private_network, ip: "10.0.0.13"
    agent2.hostmanager.aliases = %w(agent2)
  end
end  
