

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ips = false
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.synced_folder "/var/tmp//vagrant_folder", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024 
  end

  config.vm.define "puppet" do |puppet|
    #Puppet master on Centos7
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
    puppet.vm.box = "centos/7"
    puppet.vm.hostname = "puppet.example.com"
    puppet.vm.network :private_network, ip: "10.0.0.10"
    puppet.hostmanager.aliases = %w(puppet)
    puppet.vm.synced_folder "../code", "/vagrant_code"
    puppet.vm.synced_folder "../puppetserver", "/vagrant_puppetserver"
    puppet.vm.provision "shell", inline: <<-SHELL
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum update -y
      sudo yum install puppetserver -y
      sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
      sudo rm -rf /etc/puppetlabs/code
      sudo ln -s /vagrant_code /etc/puppetlabs/code
      sudo rm -rf /vagrant_puppetserver /etc/puppetlabs/puppetserver
      sudo ln -s /vagrant_puppetserver /etc/puppetlabs/puppetserver
      echo "example.com" | sudo tee /etc/puppetlabs/puppet/autosign.conf
      sudo systemctl start puppetserver.service
    SHELL
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "centos/7"
    agent1.vm.hostname = "agent1.example.com"
    agent1.vm.network :private_network, ip: "10.0.0.12"
    agent1.hostmanager.aliases = %w(agent1)
    agent1.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      sudo yum install puppet-agent -y
      sudo service puppet start
    SHELL
  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "ARTACK/debian-jessie"
    agent2.vm.hostname = "agent2.example.com"
    agent2.vm.network :private_network, ip: "10.0.0.13"
    agent2.hostmanager.aliases = %w(agent2)
  end
end  
